package com.saltfish.assistant.domain.model

data class DeviceInfo(
    val id: Long = 0,
    val uuid: String = "",
    val name: String = "",
    val model: String = "",
    val brand: String = "",
    val androidVersion: String = "",
    val sdkLevel: Int = 0,
    val securityPatch: String = "",
    val isRooted: Boolean = false,
    val totalMemory: String = "",
    val availableMemory: String = "",
    val batteryLevel: Int = 0,
    val batteryHealth: String = "",
    val batteryStatus: String = "",
    val batteryTemperature: Float = 0f,
    val isCharging: Boolean = false,
    val totalStorage: String = "",
    val availableStorage: String = "",
    val screenWidth: Int = 0,
    val screenHeight: Int = 0,
    val screenDensity: Float = 0f,
    val networkType: String = "",
    val ipAddress: String = "",
    val cpuAbi: String = "",
    val buildFingerprint: String = "",
    val appVersion: String = ""
)
